name: CI/CD - Infnet Guia

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona o repositório
      - name: Checkout do código
        uses: actions/checkout@v3

      # 2. Instala Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      # 3. Instala dependências com npm
      - name: Instala dependências
        run: npm install --legacy-peer-deps

      # 4. Lint do projeto (ignora interação)
      - name: Lint (ignora interação inicial do Next.js)
        run: |
          echo '{"extends":"next/core-web-vitals"}' > .eslintrc.json
          npm run lint || true

      # 5. Build do projeto (Next.js, React etc)
      - name: Build do projeto
        run: npm run build

      # 6. Login no Docker Hub
      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7. Build e Push da imagem
      - name: Build e Push Docker
        run: |
          docker build -t oandremotta/guia-infnet:latest .
          docker push oandremotta/guia-infnet:latest

      # 8. Cria kubeconfig a partir do secret
      - name: Cria kubeconfig a partir do secret
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
        shell: bash

      # 9. Deploy no Kubernetes
      - name: Deploy no Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
