name: CI/CD - Infnet Guia

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona o repositório
      - name: Checkout do código
        uses: actions/checkout@v3

      # 2. Instala Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'

      # 3. Instala o pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      # 4. Adiciona pnpm ao PATH (fallback)
      - name: Adiciona pnpm ao PATH manualmente (fallback)
        run: echo "${HOME}/.local/share/pnpm" >> $GITHUB_PATH

      # 5. Verifica versão do pnpm
      - name: Verifica versão do pnpm
        run: pnpm -v

      # 6. Instala dependências
      - name: Instala dependências
        run: pnpm install

      # 7. Lint
      - name: Lint
        run: pnpm lint

      # 8. Build
      - name: Build do projeto
        run: pnpm build

      # 9. Login no DockerHub
      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 10. Build e Push da imagem
      - name: Build e Push Docker
        run: |
          docker build -t oandremotta/guia-infnet:latest .
          docker push oandremotta/guia-infnet:latest

      # 11. Deploy no Kubernetes
      - name: Deploy no Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
