name: CI/CD - Infnet Guia

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Instala o pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false  # evita que ele rode "pnpm install" sozinho
          standalone: true    # adiciona o binário ao PATH automaticamente

      - name: Verifica versão do pnpm (debug)
        run: pnpm -v

      - name: Instala dependências
        run: pnpm install

      - name: Lint (ajuste se necessário)
        run: pnpm lint

      - name: Build do projeto
        run: pnpm build

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e Push Docker
        run: |
          docker build -t oandremotta/guia-infnet:latest .
          docker push oandremotta/guia-infnet:latest

      - name: Deploy no Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
