name: CI/CD - Infnet Guia

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v3

      # 2. Instala Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      # 3. Instala dependências
      - name: Instala dependências
        run: npm install --legacy-peer-deps

      # 4. (Opcional) Lint ou testes
      - name: Lint (opcional)
        run: echo "Você pode adicionar lint aqui se quiser."

      # 5. Build do projeto (se aplicável)
      - name: Build do projeto
        run: npm run build

      # 6. Login no DockerHub
      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7. Build e push da imagem
      - name: Build e Push Docker
        run: |
          docker build -t oandremotta/guia-infnet:latest .
          docker push oandremotta/guia-infnet:latest

      # 8. Deploy no Kubernetes
      - name: Deploy no Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
